package com.yuxiu.edu.model;

import java.util.Date;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.id
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_name
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_time
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    private String courseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_price
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    private Long coursePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.course_address
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    private String courseAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.teacher_name
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.expected_startdate
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    private Date expectedStartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.expected_enddate
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    private Date expectedEnddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.id
     *
     * @return the value of t_course.id
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.id
     *
     * @param id the value for t_course.id
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_name
     *
     * @return the value of t_course.course_name
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_name
     *
     * @param courseName the value for t_course.course_name
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_time
     *
     * @return the value of t_course.course_time
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public String getCourseTime() {
        return courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_time
     *
     * @param courseTime the value for t_course.course_time
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public void setCourseTime(String courseTime) {
        this.courseTime = courseTime == null ? null : courseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_price
     *
     * @return the value of t_course.course_price
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public Long getCoursePrice() {
        return coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_price
     *
     * @param coursePrice the value for t_course.course_price
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public void setCoursePrice(Long coursePrice) {
        this.coursePrice = coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.course_address
     *
     * @return the value of t_course.course_address
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public String getCourseAddress() {
        return courseAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.course_address
     *
     * @param courseAddress the value for t_course.course_address
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public void setCourseAddress(String courseAddress) {
        this.courseAddress = courseAddress == null ? null : courseAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.teacher_name
     *
     * @return the value of t_course.teacher_name
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.teacher_name
     *
     * @param teacherName the value for t_course.teacher_name
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.expected_startdate
     *
     * @return the value of t_course.expected_startdate
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public Date getExpectedStartdate() {
        return expectedStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.expected_startdate
     *
     * @param expectedStartdate the value for t_course.expected_startdate
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public void setExpectedStartdate(Date expectedStartdate) {
        this.expectedStartdate = expectedStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.expected_enddate
     *
     * @return the value of t_course.expected_enddate
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public Date getExpectedEnddate() {
        return expectedEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.expected_enddate
     *
     * @param expectedEnddate the value for t_course.expected_enddate
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public void setExpectedEnddate(Date expectedEnddate) {
        this.expectedEnddate = expectedEnddate;
    }
}