package com.yuxiu.edu.model;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.id
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.uname
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.depno
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    private String depno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.pid
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    private String pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.id
     *
     * @return the value of t_department.id
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.id
     *
     * @param id the value for t_department.id
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.uname
     *
     * @return the value of t_department.uname
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.uname
     *
     * @param uname the value for t_department.uname
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.depno
     *
     * @return the value of t_department.depno
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public String getDepno() {
        return depno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.depno
     *
     * @param depno the value for t_department.depno
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public void setDepno(String depno) {
        this.depno = depno == null ? null : depno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.pid
     *
     * @return the value of t_department.pid
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.pid
     *
     * @param pid the value for t_department.pid
     *
     * @mbggenerated Thu Aug 29 23:05:35 CST 2019
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }
}